services:
  ui:
    build:
      target: deps
    image: admin-panel-ui-dev
    volumes:
      - ./services/admin-panel-ui:/app/services/admin-panel-ui/
      - ./configs:/app/configs
      - ./package.json:/app/package.json
      # - ui-node-modules:/app/node_modules
      # - ./node_modules:/app/node_modules
    working_dir: /app/services/admin-panel-ui
    command: sh -c "yarn install && yarn workspace @services/admin-panel-ui dev"
  api:
    build:
      target: deps
    image: admin-panel-api-dev
    volumes:
      - ./services/admin-panel-api:/app/services/admin-panel-api/
      - ./configs:/app/configs
      - ./package.json:/app/package.json
      # - api-node-modules:/app/node_modules
      # - ./node_modules:/app/node_modules
    working_dir: /app/services/admin-panel-api
    command: sh -c "yarn workspace @services/admin-panel-api start:dev"

volumes:
  api-node-modules: {}
  ui-node-modules: {}
