services:
  ui:
    build:
      target: deps
    image: admin-panel-ui-dev
    env_file:
      - .env.local
    volumes:
      - ./services/admin-panel-ui:/app/services/admin-panel-ui/
      - ./configs:/app/configs
      - ./package.json:/app/package.json
      - ui-node-modules:/app/node_modules
    working_dir: /app/services/admin-panel-ui
    command: sh -c "yarn install && yarn workspace @services/admin-panel-ui dev"
  api:
    build:
      target: deps
    image: admin-panel-api-dev
    env_file:
      - .env.local
    volumes:
      - ./services/admin-panel-api:/app/services/admin-panel-api/
      - ./configs:/app/configs
      - ./package.json:/app/package.json
      - api-node-modules:/app/node_modules
    working_dir: /app/services/admin-panel-api
    command: sh -c "yarn prisma generate --schema=prisma/schema.prisma && yarn workspace @services/admin-panel-api start:dev"

volumes:
  api-node-modules: {}
  ui-node-modules: {}
