import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import {
  MaterialUIProvider,
  ReduxProvider,
  TanskackQueryProvider,
} from "@/providers";


export const metadata: Metadata = {
  title: "Admin panel",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin", "cyrillic"], weight: ["400", "700"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-toolpad-color-scheme="light">
      <body className={inter.className}>
        <TanskackQueryProvider>
          <ReduxProvider>
            <MaterialUIProvider>{children}</MaterialUIProvider>
          </ReduxProvider>
        </TanskackQueryProvider>
      </body>
    </html>
  );
}
