import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify/unstyled";
import "react-toastify/ReactToastify.css";

import { toastConfig } from "@/configs";
import {
  AuthProvider,
  MaterialUIProvider,
  TanstackQueryProvider,
} from "@/providers";

export const metadata: Metadata = {
  title: "Admin panel",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin", "cyrillic"], weight: ["400", "700"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-toolpad-color-scheme="light">
      <body className={inter.className}>
        <AuthProvider>
          <TanstackQueryProvider>
            <MaterialUIProvider>{children}</MaterialUIProvider>
            <ToastContainer {...toastConfig} />
          </TanstackQueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
