import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Suspense } from "react";

import { AppProvider } from "../components/app-provider";

import "./globals.css";

export const metadata: Metadata = {
  title: "Admin panel",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin", "cyrillic"], weight: ["400", "700"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-toolpad-color-scheme="light">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <Suspense fallback={<div>Root layout loading...</div>}>
            <AppProvider>{children}</AppProvider>
          </Suspense>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
